// Community Intelligence — curated from GitHub, HuggingFace, research papers
// Auto-scanned + manually curated. Updated April 2026.

export interface CommunityResource {
  id: string;
  category: 'model' | 'dataset' | 'tool' | 'research' | 'workflow' | 'competitor' | 'lora' | 'technique';
  name: string;
  source: string;
  url: string;
  description: string;
  impact: 'high' | 'medium' | 'low';
  impactReason: string;
  effort: 'easy' | 'medium' | 'hard'; // how hard to integrate
  status: 'available' | 'coming-soon' | 'requires-setup' | 'approved' | 'integrated';
  tags: string[];
}

export const COMMUNITY_RESOURCES: CommunityResource[] = [
  // === HIGH IMPACT — READY TO INTEGRATE ===
  {
    id: 'raresense-flux-training',
    category: 'dataset',
    name: 'RareSense Flux Jewelry Training (76 datasets, 60K+ images)',
    source: 'HuggingFace',
    url: 'https://huggingface.co/raresense',
    description: 'The largest public jewelry-specific training data. Includes necklace masks (712-7100 images), ring segmentation, hand pose annotations (DWPose), sketch-to-photo pairs, and VITON-style try-on data. Multiple datasets specifically formatted for Flux LoRA fine-tuning.',
    impact: 'high',
    impactReason: 'Fine-tuning a Flux LoRA on this data would create a jewelry-specific model that eliminates hallucination. No other platform has this. Would make our generations dramatically more accurate than any competitor.',
    effort: 'hard',
    status: 'available',
    tags: ['fine-tuning', 'dataset', 'flux', 'jewelry-specific', 'lora'],
  },
  {
    id: 'catvton-flux',
    category: 'lora',
    name: 'CatVTON-Flux (Virtual Try-On LoRA, 37M params)',
    source: 'GitHub',
    url: 'https://github.com/nftblackmagic/catvton-flux',
    description: 'Extremely lightweight LoRA (37.4M checkpoint) for FLUX.1-Fill-dev. Handles virtual try-on with dual image input (person + garment). Could be adapted for jewelry on hands/necks.',
    impact: 'high',
    impactReason: 'Our try-on feature uses basic text prompts. CatVTON uses actual image compositing — the jewelry would be pixel-accurately placed on the body, not hallucinated.',
    effort: 'medium',
    status: 'available',
    tags: ['try-on', 'lora', 'flux', 'compositing'],
  },
  {
    id: 'flux2-vton-lora',
    category: 'lora',
    name: 'Flux2-VTON-LoRA (Virtual Try-On Fine-Tune)',
    source: 'GitHub',
    url: 'https://github.com/LightCooling/flux2-vton-lora',
    description: 'LoRA fine-tuning for FLUX.2 specifically for virtual try-on. Image-to-image pipeline. Could be adapted from clothing to jewelry.',
    impact: 'high',
    impactReason: 'Combined with jewelry segmentation data, this could create the first accurate AI jewelry try-on system. Competitors like SellerPic only do static images.',
    effort: 'medium',
    status: 'available',
    tags: ['try-on', 'lora', 'flux2', 'fine-tuning'],
  },
  {
    id: 'ip-adapter',
    category: 'tool',
    name: 'IP-Adapter (Reference Image Identity Preservation)',
    source: 'GitHub',
    url: 'https://github.com/tencent-ailab/IP-Adapter',
    description: '22M parameter adapter (6.5K stars). Enables reference image prompting with identity preservation. Far superior to basic image_input — maintains exact visual identity across generations.',
    impact: 'high',
    impactReason: 'Would solve jewelry design consistency across multiple shots. Our current image_input approach loses details. IP-Adapter preserves them.',
    effort: 'medium',
    status: 'available',
    tags: ['consistency', 'reference-image', 'adapter', 'identity'],
  },
  {
    id: 'controlnet',
    category: 'tool',
    name: 'ControlNet (Depth/Edge/Pose Control)',
    source: 'GitHub',
    url: 'https://github.com/lllyasviel/ControlNet',
    description: '31K+ stars. Adds depth maps, edge detection, normal maps, and pose control to generation. Specific control over where things go in the image.',
    impact: 'high',
    impactReason: 'Makes try-on pixel-accurate — depth maps ensure rings sit on fingers correctly. Also enables precise product placement on surfaces. Key technology we\'re missing.',
    effort: 'hard',
    status: 'requires-setup',
    tags: ['control', 'depth', 'pose', 'try-on', 'placement'],
  },
  {
    id: 'glamtry-paper',
    category: 'research',
    name: 'GlamTry: Virtual Try-On for High-End Accessories',
    source: 'arXiv',
    url: 'https://arxiv.org/pdf/2409.14553',
    description: 'Research paper specifically about virtual try-on for jewelry and accessories. Uses MediaPipe Hand Landmarker for precise ring/bracelet placement on hands.',
    impact: 'high',
    impactReason: 'Direct academic research for our core use case. Their hand landmark approach would make ring try-on work as well as clothing try-on works today.',
    effort: 'hard',
    status: 'available',
    tags: ['try-on', 'research', 'hand-detection', 'academic'],
  },
  {
    id: 'in-context-lora',
    category: 'technique',
    name: 'In-Context LoRA (Multi-Task Generation)',
    source: 'GitHub',
    url: 'https://github.com/ali-vilab/In-Context-LoRA',
    description: 'Alibaba\'s technique for doing virtual try-on, product design, and object placement with a single LoRA. Community workflows for ComfyUI available.',
    impact: 'high',
    impactReason: 'One LoRA that handles try-on + product placement + style transfer. Would replace our 3 separate approaches with one unified, better system.',
    effort: 'hard',
    status: 'available',
    tags: ['lora', 'multi-task', 'try-on', 'style-transfer'],
  },
  {
    id: 'recraft-v4',
    category: 'model',
    name: 'Recraft V4 (#1 on HuggingFace benchmarks)',
    source: 'HuggingFace',
    url: 'https://huggingface.co/recraft-ai',
    description: 'Proven #1 on HuggingFace image gen benchmarks. Built-in brand styling tools, SVG export for scalable vectors. Major upgrade from V3 we currently use.',
    impact: 'high',
    impactReason: 'Direct upgrade to our existing Recraft integration. Better quality, brand consistency tools would help our brand guidelines feature.',
    effort: 'easy',
    status: 'available',
    tags: ['model', 'image', 'benchmark-leader', 'brand-styling'],
  },
  {
    id: 'flux2-model',
    category: 'model',
    name: 'Flux 2 (Best Photorealism 2026)',
    source: 'Black Forest Labs',
    url: 'https://blackforestlabs.ai',
    description: 'Ranked #1 for photorealism. Skin textures, lighting imperfections, natural poses that other models can\'t match. Successor to Flux 1.1 Pro Ultra we currently use.',
    impact: 'high',
    impactReason: 'Direct replacement for our Flux Ultra (which we downgraded for jewelry hallucination). Flux 2\'s improved understanding may fix the issues V1 had.',
    effort: 'easy',
    status: 'coming-soon',
    tags: ['model', 'image', 'photorealism', 'upgrade'],
  },
  {
    id: 'seedance-reference-imgs',
    category: 'technique',
    name: 'Seedance 1.5 Pro Reference Images Feature',
    source: 'Replicate',
    url: 'https://replicate.com/bytedance/seedance-1.5-pro',
    description: 'Seedance supports 1-4 reference_images for character/object consistency. We\'re using it but NOT passing the reference_images parameter — only using the image (first frame) param.',
    impact: 'high',
    impactReason: 'Passing our jewelry reference images via reference_images would dramatically improve design consistency in video without any new model or tool.',
    effort: 'easy',
    status: 'available',
    tags: ['video', 'consistency', 'quick-win', 'already-have'],
  },
  // === MEDIUM IMPACT ===
  {
    id: 't-lora',
    category: 'technique',
    name: 'T-LoRA (Single Image Custom Diffusion)',
    source: 'GitHub (AAAI 2026)',
    url: 'https://github.com/ControlGenAI/T-LoRA',
    description: 'AAAI 2026 paper. Customize a diffusion model from a SINGLE image without overfitting. Could train a LoRA for each jewelry piece from just one product photo.',
    impact: 'medium',
    impactReason: 'Customers upload ONE photo. T-LoRA could create a piece-specific model from that single photo, ensuring every generation perfectly matches their piece.',
    effort: 'hard',
    status: 'available',
    tags: ['lora', 'single-image', 'customization', 'academic'],
  },
  {
    id: 'sam2',
    category: 'tool',
    name: 'SAM 2 (Segment Anything Model 2)',
    source: 'Meta AI',
    url: 'https://ai.meta.com/research/sam2',
    description: 'Segment any object in images and video. Auto-detect and isolate jewelry pieces from any photo.',
    impact: 'medium',
    impactReason: 'Better than our basic background removal. Could auto-detect ring vs necklace vs earring, segment precisely, and enable advanced compositing.',
    effort: 'medium',
    status: 'available',
    tags: ['segmentation', 'detection', 'background-removal'],
  },
  {
    id: 'bria-rmbg',
    category: 'tool',
    name: 'Bria RMBG 2.0 (Pro Background Removal)',
    source: 'fal.ai',
    url: 'https://fal.ai',
    description: 'Professional-grade background removal trained on licensed data. Handles reflective/transparent surfaces better than basic rembg.',
    impact: 'medium',
    impactReason: 'Our current remove-bg model (lucataco/remove-bg) may struggle with reflective jewelry. Bria is specifically trained for challenging surfaces.',
    effort: 'easy',
    status: 'available',
    tags: ['background-removal', 'reflective-surfaces'],
  },
  {
    id: 'jewelry-segmentation-4807',
    category: 'dataset',
    name: 'Jewelry Segmentation Dataset (4,807 images)',
    source: 'Roboflow',
    url: 'https://universe.roboflow.com',
    description: '4,807 jewelry images with segmentation annotations. CC BY 4.0 license.',
    impact: 'medium',
    impactReason: 'Training a jewelry detector would auto-classify uploads — ring vs necklace vs bracelet. Eliminates the "what type?" question in our chatbot.',
    effort: 'medium',
    status: 'available',
    tags: ['dataset', 'segmentation', 'classification'],
  },
  {
    id: 'hands-jewelry-11k',
    category: 'dataset',
    name: '11K Hands with Jewelry Segmentation',
    source: 'Zenodo',
    url: 'https://zenodo.org',
    description: '11,076 hand photos with segmentation masks from 190 people. Diverse hand types, ages, skin tones.',
    impact: 'medium',
    impactReason: 'Training data for accurate ring and bracelet placement on diverse hands. Would fix our try-on proportions.',
    effort: 'medium',
    status: 'available',
    tags: ['dataset', 'hands', 'try-on', 'diversity'],
  },
  {
    id: 'wan22-ti2v',
    category: 'model',
    name: 'Wan2.2-TI2V-5B (Text+Image to Video)',
    source: 'HuggingFace',
    url: 'https://huggingface.co/models?pipeline_tag=image-to-video',
    description: 'Latest Wan video model. Best balance of quality, speed, and accessibility. Supports text-to-image-to-video pipeline natively.',
    impact: 'medium',
    impactReason: 'Could be a cheaper/faster alternative to Veo 3 for jewelry product videos. Worth testing.',
    effort: 'easy',
    status: 'available',
    tags: ['model', 'video', 'image-to-video'],
  },
  {
    id: 'comfyui-jewelry-workflow',
    category: 'workflow',
    name: 'ComfyUI Jewelry Product Photography Workflow',
    source: 'RunningHub',
    url: 'https://runninghub.ai',
    description: 'Community-built deterministic workflow for diamond ring product photography with precise background and lighting control.',
    impact: 'medium',
    impactReason: 'ComfyUI gives deterministic control that API-based generation can\'t match. Could be used as a secondary pipeline for high-fidelity work.',
    effort: 'hard',
    status: 'requires-setup',
    tags: ['workflow', 'comfyui', 'deterministic', 'product-photo'],
  },
  {
    id: 'pyiqa',
    category: 'tool',
    name: 'IQA-PyTorch (Image Quality Assessment)',
    source: 'GitHub',
    url: 'https://github.com/chaofengc/IQA-PyTorch',
    description: '3.2K stars. Unified interface for SSIM, LPIPS, FID, NIMA quality metrics. Auto-score generated images.',
    impact: 'medium',
    impactReason: 'Could auto-rate every generated image for technical quality BEFORE showing to user. Filter out bad generations automatically.',
    effort: 'hard',
    status: 'available',
    tags: ['quality', 'metrics', 'auto-evaluation'],
  },
  // === COMPETITORS ===
  {
    id: 'formanova',
    category: 'competitor',
    name: 'FormaNova — AI Photography for Jewelry',
    source: 'formanova.ai',
    url: 'https://formanova.ai',
    description: 'Purpose-built AI photography platform exclusively for jewelry. Maintains the awesome-jewelry-ai GitHub repo. Our closest competitor.',
    impact: 'high',
    impactReason: 'Watch their features. They are the only other jewelry-specific AI platform. Their research repo is a goldmine of papers and datasets we should track.',
    effort: 'easy',
    status: 'available',
    tags: ['competitor', 'jewelry-specific', 'watch'],
  },
  {
    id: 'mintly',
    category: 'competitor',
    name: 'Mintly — AI Jewelry Ads (100% Text Preservation)',
    source: 'usemintly.com',
    url: 'https://usemintly.com',
    description: 'Claims 100% preservation of product text, logos, and labels. Turns product images into polished static ads and video creatives.',
    impact: 'medium',
    impactReason: 'Their text preservation claim is exactly our hallucination challenge. Study their approach for engravings and lettered pieces.',
    effort: 'easy',
    status: 'available',
    tags: ['competitor', 'text-preservation', 'ads'],
  },
  {
    id: 'jewelryai-video',
    category: 'competitor',
    name: 'JewelryAI.video — 360° Rotation & Scene Videos',
    source: 'jewelryai.video',
    url: 'https://jewelryai.video',
    description: 'Focused on rotation videos and scene videos for jewelry e-commerce. Simple but effective.',
    impact: 'medium',
    impactReason: 'We have rotation now via Seedance. But their scene video templates might inspire new campaign templates for us.',
    effort: 'easy',
    status: 'available',
    tags: ['competitor', 'video', 'rotation', 'ecommerce'],
  },
  {
    id: 'blng-ai',
    category: 'competitor',
    name: 'BLNG — Creative Suite for Jewelry',
    source: 'blng.ai',
    url: 'https://blng.ai',
    description: 'Full creative suite specifically for the jewelry industry. New entrant.',
    impact: 'medium',
    impactReason: 'New competitor. Monitor their feature set and positioning.',
    effort: 'easy',
    status: 'available',
    tags: ['competitor', 'creative-suite', 'watch'],
  },
];

export function getResourcesByImpact(impact: 'high' | 'medium' | 'low') {
  return COMMUNITY_RESOURCES.filter(r => r.impact === impact);
}

export function getResourcesByCategory(category: string) {
  return COMMUNITY_RESOURCES.filter(r => r.category === category);
}
